Biomes invoices
sora-xor/sora-accounting pull request #2
Opened 2023-06-15 13:13 UTC by WRRicht3r

Added invoices for SORA/ Polka Biome

2023-06-16 03:10 UTC, Tieumsan commented
Some of the dates in the file title don't correspond to the dates in the file. Please review and correct

2023-06-16 09:21 UTC, WRRicht3r commented
@Tieumsan updated the titles and added the latest invoice from Band

2023-06-20 14:26 UTC, WRRicht3r commented
Hello @Tieumsan @takemiyamakoto can this PR be reviewed and approved please? An invoice within the commit has been paid

2023-06-21 10:54 UTC, takemiyamakoto approved these changes

2023-06-21 17:03 UTC, Tieumsan requested changes

2023-06-21 17:03 UTC, Tieumsan commented on Band Protocol/June 2023_Sora Maintenance and Infra Invoice.pdf
the Band Protocol/SORA Implementation Invoice.pdf file in the folder does not have the same naming (no date)

2023-06-21 17:03 UTC, Tieumsan commented on Polka Biome/Polka Biome - Community grant request Jan23.pdf
naming and date still inconsistent

2023-06-21 17:03 UTC, Tieumsan commented on Polka Biome/Polka Biome - Community grant request Jan23.pdf
please recheck the others as well

2023-06-22 08:48 UTC, Tieumsan approved these changes

2023-06-22 08:50 UTC, merged